var tabla = [
	["Pictionary","Juego","Dibujar","Lápiz","Marca","Tablero"],
	["Esposas","Arresto","Policía","Mano","Preso","Muñeca"],
	["Monja","Habito","Religión","Hermana","Convento","Novicia"],
	["Museo","Arte","Edificio","Pinturas","Exhibición","Colecciones"],
	["Pescador","Pez","Caña","Anzuelo","Carnada","Lombriz"],
	["Carne","Vaca","Asado","Comer","Milanesa","Hamburguesa"],
	["Recreo","Patio","Escuela","Jugar","Campana","Tiempo"],
	["Rímel","Ojos","Maquillaje","Cepillo","Cosmético","Pestaña"],
	["Nieve","Blanca","Agua","Invierno","Esquiar","Frío"],
	["Cirujano","Hospital","Anestesia","Operación","Doctor","Bisturí"],
	["Payaso","Circo","Nariz","Zapatones","Bofetada","Reír"],
	["Obelisco","Monumento","Buenos Aires","Corrientes","Símbolo","República"],
	["Hoguera","Madera","Quemar","Leña","Fuego","Campamento"],
	["Chatarra","Autos","Coche","Hierro","Basura","Metal"],
	["Barca Hinchable","Piscina","Remos","Agua","Navegar","Inflar"],
	["Samurái","Soldado","Espada","Japón","Antiguo","Hara-Kiri"],
	["Diamante","Duro","Quilates","Joyas","Brillante","Piedra"],
	["Nuez","Fruta","Árbol","Navidad","Almendra","Avellana"],
	["Lápida","Piedra","Cementerio","Epitafio","Tumba","Sepultura"],
	["Amígdalas","Glándulas","Garganta","Inflamar","Operación","Angina"],
	["Osram","Luz","Marca","Bombilla","Electricidad","Philips"],
	["Dibujo","Lápiz","Pintar","Garabato","Papel","Retrato"],
	["Botas","Pies","Caminar","Zapatos","Cuero","Caballo"],
	["Pasa De Uva","Corinto","Semillas","Arruga","Fruta","Seca"],
	["Pila","Batería","Recargable","Duracell","Energizer","Linterna"],
	["Salchicha","Mostaza","Frankfurt","Alemania","Wiener","Comer"],
	["Botón","Camisa","Ojal","Cierre","Abrochar","Manga"],
	["Espejo","Vidrio","Retrovisor","Reflejar","Ver","Pared"],
	["Albóndiga","Redonda","Comida","Carne","Cacerola","Bola"],
	["Zurdo","Mano","Izquierda","Derecha","Comunista","Maradona"],
	["Superman","Kriptonita","Lois Lane","Clark Kent","Película","Volar"],
	["Radio","Fm","Am","Dial","Noticias","Sintonía"],
	["Bowling","Strike","Juego","Cancha","Tirar","Canaleta"],
	["Moño","Nudo","Corbata","Atar","Seda","Regalo"],
	["Iceberg","Hielo","Polo","Glaciar","Flotante","Titanic"],
	["Vela","Luz","Cera","Candelabro","Cumpleaños","Mecha"],
	["Avestruz","Animal","Plumas","Esconder","Correr","Ala"],
	["Descifrar","Jeroglífico","Código","Leer","Secreto","Clave"],
	["Víbora","Cleopatra","Serpiente","Culebra","Reptil","Veneno"],
	["Pipa","Fumar","Tabaco","Cigarrillo","Humo","Nicotina"],
	["Harén","Muchas","Mujeres","Sultán","Musulmán","Concubinas"],
	["Chismoso","Noticia","Soplón","Criticar","Rumores","Entrometido"],
	["Juez","Sentencia","Jurado","Fiscal","Tribunal","Señoría"],
	["Caja","Envase","Cartón","Guardar","Cofre","Recipiente"],
	["Cáscara","Banana","Recubrimiento","Envoltura","Naranja","Piel"],
	["Acné","Cara","Espinilla","Adolescente","Punto","Grano"],
	["Espermatozoide","Pene","Eyacular","Ovulo","Testículos","Semen"],
	["Sorpresa","Cumpleaños","Regalo","Fiesta","Inesperada","Imprevisto"],
	["Kodak","Cámara","Fotografía","Film","Marca","Revelar"],
	["Científico","Descubrimiento","Experimento","Laboratorio","Microscopio","Tubo De Ensayo"],
	["Arbitro","Juez","Reglas","Deportes","Fútbol","Linier"],
	["Cucaracha","Insecto","Cocina","Bicho","Nocturno","Comida"],
	["Circuito","Carrera","Competición","Pista","Fórmula 1","Recorrido"],
	["Mayonesa","Mostaza","Hellmann’s","Amarilla","Condimento","Sándwich"],
	["Madera","Tronco","Leños","Carpintero","Árboles","Tabla"],
	["Pezón","Pechos","Tetas","Mujer","Punta","Leche"],
	["Plagio","Copia","Imitación","Ideas","Delito","Falso"],
	["Manguera","Regar","Agua","Canilla","Caño","Goma"],
	["Navidad","Diciembre","Papa Noel","Villancicos","Arbolito","Nacimiento"],
	["Risa","Ridículo","Cómico","Carcajada","Chiste","Broma"],
	["Pimpollo","Capullo","Botón","Flor","Rosa","Cerrado"],
	["Polvo","Limpio","Sucio","Tierra","Plumero","Muebles"],
	["Circulo","Anillo","Redondo","Compás","Línea","Curva"],
	["Estación","Terminal","Tren","Parada","Anden","Bonetería"],
	["Ostra","Perla","Mar","Bivalvo","Marisco","Comer"],
	["Calefacción","Invierno","Estufa","Aire","Caldera","Frío"],
	["Manzana","Comer","Sidra","Verde","Rojo","Fruta"],
	["Mate","Yerba","Bombilla","Agua","Amargo","Azúcar"],
	["Trapo","Bayeta","Secar","Platos","Cocina","Tela"],
	["Cóctel","Alcohol","Trago","Copa","Mezcla","Bebida"],
	["Sillón","Respaldo","Cómodo","Asiento","Sentarse","Sofá"],
	["Bosque","Plantas","Árboles","Animales","Madera","Selva"],
	["Valiente","Cobarde","Miedo","Defender","Héroe","Salvar"],
	["Uña","Manicura","Limar","Dedo","Esmalte","Pintar"],
	["Loro","Pájaro","Hablar","Plumas","Verde","Pirata"],
	["Rio","Mar","Pescar","Navegar","Corriente","Agua"],
	["Diario","Periódico","Matutino","Vespertino","Quiosco","Canillita"],
	["Modista","Coser","Vestido","Mujer","Sastre","Probar"],
	["Insulto","Ofensa","Palabras","Gritar","Enojado","Decir"],
	["Escarapela","Azul","Blanca","Argentina","Solapa","Redonda"],
	["Salmon","Río","Rosado","Trucha","Ahumado","Pez"],
	["Chupete","Boca","Bebe","Niño","Mamadera","Teta"],
	["Armadura","Metal","Usar","Traje","Caballero","Protección"],
	["Batidora","Thermomix","Triturar","Electrodomésticos","Rallar","Moler"],
	["Mes","Doce","Días","Semanas","Año","Calendario"],
	["Pasto","Verde","Césped","Jardín","Hierba","Cortar"],
	["Mono","Chimpancé","Chita","Gorila","Tarzán","Simio"],
	["Caracol","Cuernos","Espiral","Arrastrarse","Lento","Jardín"],
	["Felicidad","Bienestar","Alegría","Dichoso","Suerte","Desgracia"],
	["Laberinto","Perderse","Camino","Entrada","Salir","Lugar"],
	["Araña","Insecto","Tarántula","Tejes","Tela","Ratas"],
	["Cepillo De Dientes","Cerdas","Boca","Pasta","Flúor","Limpiar"],
	["Curita","Corte","Sangre","Venda","Protección","Lastimadura"],
	["Bigotes","Mostachos","Boca","Pelo","Barba","Labio"],
	["Ambulancia","Camilla","Hospital","Vehículo","Herido","Sirena"],
	["Caño","Tubo","Agua","Electricidad","Redondo","Hueco"],
	["Copa","Beber","Agua","Cristal","Vidrio","Vaso"],
	["Motor","Mover","Coche","Capot","Maquina","Mecánica"],
	["Camisa","Corbata","Pantalón","Manga","Botón","Saco"],
	["Martillo","Clavo","Maza","Herramienta","Golpear","Dedo"],
	["Preservativo","Profiláctico","Condón","Látex","Sida","Pene"],
	["Toalla","Manos","Mojado","Secarse","Lavatorio","Baño"],
	["Barba","Afeitar","Bigote","Hombre","Tijeras","Pelo"],
	["Alpinista","Escalar","Trepar","Montaña","Cuerdas","Himalaya"],
	["Basura","Camión","Bolsa","Contenedor","Reciclar","Residuos"],
	["Cepo","Parquímetro","Estacionar","Multa","Auto","Grúa"],
	["Apagar","Prender","Encender","Interruptor","Sofocar","Luz"],
	["Curandero","Doctor","Tribu","Enfermo","Remedio","Medico"],
	["Jirafa","Alto","Animal","Cuello","Manchas","Largo"],
	["Testículos","Genitales","Pene","Hombre","Semen","Bolas"],
	["Plano","Construir","Guía","Edificio","Arquitecto","Mapa"],
	["Gato","Animal","Felino","Arañar","Maullido","Ronroneo"],
	["Invitado","Boda","Cumpleaños","Fiesta","Amigos","Convidar"],
	["Infantil","Bebe","Juguete","Niño","Pequeño","Nene"],
	["Píldora","Remedio","Medicina","Enfermo","Pastilla","Tragar"],
	["Ventilador","Aire","Techo","Verano","Aspas","Girar"],
	["Venda","Torcedura","Gasa","Medico","Farmacia","Herida"],
	["Tomate","Rojo","Verdura","Perita","Salsa","Pizza"],
	["Canario","Pájaro","Jaula","Canto","Amarillo","Piolín"],
	["Guardapolvo","Blanco","Escuela","Primaria","Maestra","Alumno"],
	["Cenizas","Fuego","Fumar","Polvo","Quemar","Cigarrillo"],
	["Lavarropas","Maquina","Electrodoméstico","Tambor","Centrifugar","Jabón"],
	["Barro","Lluvia","Tierra","Lodo","Agua","Fango"],
	["Flan","Leche","Molde","Postre","Huevos","Caramelo"],
	["Cosquillas","Dedos","Hacer","Pies","Sensación","Risa"],
	["Anchoa","Sardina","Pescado","Lata","Comida","Salado"],
	["Girasol","Planta","Semillas","Aceite","Flor","Amarillo"],
	["Telefoneo","Numero","Llamar","Móvil","Tomo","Ocupado"],
	["Critico","Película","Opinión","Teatro","Arte","Comentar"],
	["Albino","Blanco","Ojos","Cara","Piel","Color"],
	["Semana","Mes","Cuatro","Tiempo","Siete","Días"],
	["Lagarto","Cocodrilo","Animal","Sol","Reptil","Pequeño"],
	["Alarma","Robo","Casa","Banco","Atraco","Ladrón"],
	["Mochila","Bolso","Hombro","Caminata","Llevar","Espalda"],
	["Mariposa","Larva","Volar","Insecto","Flores","Alas"],
	["Drácula","Conde","Sangre","Transilvania","Colmillos","Vampiro"],
	["Jarrón","Flores","Agua","Adorno","Porcelana","Cristal"],
	["Café","Taza","Grano","Moler","Negro","Filtro"],
	["Mártir","Santo","Muerte","Religión","Sacrificio","Sufrir"],
	["Lotería","Billete","Números","Gordo","Sorteo","Juego"],
	["Medianoche","Cenicienta","Mediodía","Final","Hora 24","Doce En Punto"],
	["Jorobado","Encorvado","Espalda","Deforme","Giba","Notre Dame"],
	["Jamón","Carne","Fiambre","Cerdo","Ibérico","Curado"],
	["Océano Atlántico","Pacifica","Agua Salada","Costa","Mar","Olas"],
	["Menor De Edad","Chico","Niño","18 Años","Joven","Mayor"],
	["Acupuntura","Clavar","Agujas","Cuerpo","Chino","Doctor"],
	["Computadora","Programa","Impresora","Disquete","Monitor","Teclado"],
	["Publico","Aplauso","Gente","Privado","Espectáculo","Teatro"],
	["Ladrido","Perro","Voz","Asustar","Morder","Guardián"],
	["Torre Eiffel","París","Francia","Símbolo","Ciudad","Luz"],
	["Opera","Cantar","Escena","Música","Pavarotti","Tenor"],
	["Universidad","Estudios","Cátedra","Facultad","Carrera","Terciario"],
	["Cemento","Cal","Arena","Loma Negra","Ladrillos","Obra"],
	["Lengua","Boca","Gusto","Chupar","Hablar","Idioma"],
	["Túnel","Agujero","Subterráneo","Pasar","Montañas","Puente"],
	["Torta","Dulce","Postre","Cumpleaños","Pastel","Velitas"],
	["Oro","Dientes","Metal Precioso","Quilate","Anillo","Caro"],
	["Batuta","Director","Orquesta","Palo","Varilla","Músicos"],
	["Coche Fúnebre","Cementerio","Llevar","Funeral","Muerto","Vehículo"],
	["Big Ben","Inglaterra","Londres","Monumento","Reloj","Tiempo"],
	["Sandia","Jugosa","Verano","Fruta","Semilla","Verde"],
	["Puerto","Mar","Muelle","Barco","Carga","Anclar"],
	["Panadería","Pistola","Harina","Horno","Leña","Baguette"],
	["Cometa","Estrella","Cielo","Espacio","Astro","Halley"],
	["Naranja","Fruta","Jugo","Amarillo","Cítrico","Limón"],
	["Leche","Bebida","Blanco","Pascual","Puleva","Vaca"],
	["Gaseosa","Gas","Burbujas","Casera","Sifón","Agua"],
	["Minifalda","Pollera","Ropa","Mujer","Corta","Vestido"],
	["Emergencia","Ambulancia","Urgencia","S.O.S.","Llamada","Accidente"],
	["Geometría","Ángulos","Escuela","Escuadra","Compas","Polígonos"],
	["Shell","Gasolina","Combustible","Lubricante","Estación De Servicio","Repostar"],
	["Bufanda","Frío","Lana","Boca","Proteger","Cuello"],
	["Isla","Océano","Mar","Tierra","Rodeada","Agua"],
	["Tarzán","Chita","Jane","Selva","Grito","Lianas"],
	["Campo","Cultivar","Ciudad","Gaucho","Vacas","Rural"],
	["Carretilla","Llevar","Rueda","Arena","Obra","Tierra"],
	["Crimen","Cadáver","Asesinato","Victima","Homicidio","Matar"],
	["Vereda","Calle","Circular","Peatón","Baldosa","Cordón"],
	["Palmera","Dátil","Coco","Árbol","Mono","Trópico"],
	["Botiquín","Baño","Espejo","Remedios","Guardar","Armario"],
	["Terremoto","Derrumbe","Sismo","Temblor","Tierra","Movimiento"],
	["Pimienta","Cocina","Picante","Sabor","Condimento","Sal"],
	["Skate","Patinete","Monopatín","Cuatro","Ruedas","Tabla"],
	["Fuego","Fósforo","Llamas","Hoguera","Quemar","Leña"],
	["Fantasma","Sábana","Miedo","Cadenas","Castillo","Espíritu"],
	["Eructo","Ruido","Bebé","Comer","Boca","Provecho"],
	["Angulo","Recta","Grado","Geometría","Polígono","Lado"],
	["Gelatina","Flan","Comer","Postre","Helado","Transparente"],
	["Helicóptero","Avión","Volar","Rotor","Vertical","Hélice"],
	["Lacoste","Polo","Marca","Ropa","Cocodrilo","Reptil"],
	["Mamadera","Leche","Tetina","Comer","Bebe","Chupar"],
	["Balanza","Pesar","Platillo","Kilos","Farmacia","Gramo"],
	["Bostezo","Boca","Abrir","Sueño","Aburrimiento","Contagioso"],
	["Naufrago","Isla","Barco","Palmera","Barba","Botella"],
	["Polen","Flores","Abeja","Mariposa","Planta","Polvo"],
	["Dinosaurio","Prehistórico","Grande","Gigante","Reptil","Antigüedad"],
	["Autocine","Película","Coche","Estacionar","Aire Libre","Ver"],
	["Helado","Frío","Crema","Palito","Cucurucho","Bombón"],
	["Abanderado","Colegio","Alumno","Acto","Elegido","Notas"],
	["Peine","Dientes","Cabeza","Pelo","Cepillo","Espejo"],
	["Insecto","Animal","Patas","Pequeño","Pica","Antenas"],
	["Mapa","Cartografía","Atlas","Geografía","Rutas","Globo Terráqueo"],
	["Tapa","Rosca","Cerrar","Cacerola","Hermética","Cubierta"],
	["Quiniela","Fútbol","Equis","Lotería","Apuesta","Números"],
	["Embudo","Botella","Liquido","Damajuana","Hueco","Llenar"],
	["Escuela","Guardapolvo","Maestra","Recreo","Aula","Alumnos"],
	["Espada","Acero","Arma","Cuchillo","Esgrima","Sable"],
	["Escaparse","Huir","Quedarse","Evadirse","Rápido","Correr"],
	["Actor","Artista","Interprete","Películas","Teatro","Televisión"],
	["H&S","Champú","Pelo","Lavar","Marca","P&G"],
	["Arruga","Planchar","Línea","Cara","Piel","Viejo"],
	["Salvavidas","Nadar","Pileta","Playa","Flotar","Ahogarse"],
	["Imán","Hierro","Atracción","Brújula","Norte","Magnético"],
	["Venus","Mercurio","Plutón","Espacio","Planeta","Luna"],
	["Manteca","Alimento","Vaca","Leche","Margarina","Untar"],
	["Palmada","Amistoso","Golpecito","Espalda","Mano","Aplauso"],
	["Champagne","Francés","Brindar","Corcho","Vino","Sidra"],
	["Kamikaze","Guerra","Suicida","Piloto","Japonés","Aviador"],
	["Irritar","Alterar","Joder","Molestar","Enojar","Nervios"],
	["Cinta De Video","Película","Casete","TV","Cine","Videoclub"],
	["Película","Cine","Pantalla","Film","Video","Actores"],
	["Tronco","Árbol","Leña","Madera","Rama","Raíz"],
	["Carnaval","Bombitas","Mojar","Río De Janeiro","Corso","Comparsas"],
	["Neumonía","Enfermedad","Frío","Bronquios","Pulmón","Inflamación"],
	["Profesión","Carrera","Trabajo","Laburo","Ocupación","Oficio"],
	["Invisible","Hombre","Ver","Mirar","Transparente","Fantasma"],
	["Guerra","Batalla","Armas","Ejercito","Soldados","Combate"],
	["Moda","Ropa","Alta Costura","Onda","Temporada","Desfile"],
	["Recital","Concierto","Instrumentos","Escenario","Grupo","Música"],
	["Estéril","Embarazo","Esperma","Fértil","Hijos","Procrear"],
	["Velocímetro","Coche","R.P.M.","Reloj","Tacómetro","Aguja"],
	["Bicicleta","2 Ruedas","Velódromo","Moto","Manubrio","Pedal"],
	["Prueba","Beber","Catar","Colegio","Test","Examen"],
	["Melón","Fruta","Verano","Rodaja","Sandia","Semillas"],
	["Carga","Bultos","Pesada","Camión","Barco","Tren"],
	["Antifaz","Ojos","Tapar","Mascara","Carnaval","Cara"],
	["Día","Noche","Sol","Horas","Semana","Despierto"],
	["Cuchillo","Cuchara","Tenedor","Cortar","Cubierto","Afilado"],
	["Gas","Estufa","Cocinar","Bombona","Calefacción","Natural"],
	["Idioma","Lengua","País","Diccionario","Traducir","Estudiar"],
	["Gol","Pelota","Marcar","Puntuación","Fútbol","Portería"],
	["Granero","Trigo","Edificio","Silo","Cereales","Campo"],
	["Estribos","Montura","Ensillar","Pies","Espuelas","Caballo"],
	["Oxigeno","Respirar","Aire","Atmosfera","Hidrogeno","Gas"],
	["Congreso","Cámara","Senado","Gobierno","Diputados","Poder Legislativo"],
	["Software","Computadora","Programa","Aplicación","Lenguaje","Hardware"],
	["Aduana","Control","Frontera","Pasaporte","Declarar","Contrabando"],
	["Vidriera","Negocio","Mirar","Calle","Galería","Cristal"],
	["Tetera","Infusión","Calentar","Hervir","Agua","Preparar"],
	["Hombro","Cuerpo","Espalda","Brazo","Parte","Cuello"],
	["Lluvia","Agua","Caer","Paraguas","Tiempo","Mojar"],
	["Gimnasia","Ejercicio","Pesas","Aparatos","Deporte","Aerobic"],
	["Asociación","Club","Grupo","Organización","Sociedad","Compañía"],
	["Espuelas","Jinete","Montar","Caballo","Metal","Puntas"],
	["Baño","Espejo","Aseo","Ducha","Lavarse","Inodoro"],
	["Valija","Viajar","Guardar","Equipaje","Ropa","Llevar"],
	["Desnudo","Vestido","En Cueros","Ropa","En Bolas","Sin"],
	["Amargo","Azúcar","Dulce","Café","Agrio","Cerveza"],
	["Ruleta","Números","Bolita","Negro","Rojo","Casino"],
	["Regalo","Cumpleaños","Dar","Navidad","Presente","Obsequio"],
	["Deseo","Querer","Capricho","Sexual","Tener","Pedir"],
	["Adivinanza","Acertijo","Saber","Misterio","Descifrar","Descubrir"],
	["Banda","Música","Orquesta","Grupo","Instrumentos","Marchas"],
	["Candado","Cerradura","Llaves","Ladrón","Seguridad","Combinación"],
	["Mesa","Silla","Mueble","Comer","Patas","Mantel"],
	["Torno","Muela","Caries","Dentista","Dolor","Boca"],
	["Zoológico","Animales","Jaulas","Jardín Botánico","Acuario","Cautiverio"],
	["Cataratas De Iguazú","Agua","Argentina","Brasil","Turistas","Cascada"],
	["Microbio","Pequeño","Infección","Antibióticos","Vacuna","Enfermedad"],
	["Coñac","Copa","Bebida","Alcohol","Licor","Brandy"],
	["Cárcel","Barrotes","Prisión","Celda","Delincuente","Ladrón"],
	["Marco","Foto","Cuadro","Retrato","Puerta","Pintura"],
	["Molino De Viento","Campo","Aspas","Holanda","Don Quijote","Harina"],
	["Paisaje","Viaje","Campo","Panorama","Horizonte","Vista"],
	["Pava","Mate","Hervir","Agua","Calentar","Te"],
	["Karate","Artes Marciales","Ninja","Judo","Oriental","Bruce Lee"],
	["Caja Fuerte","Combinación","Ladrones","Guardar","Robar","Joyas"],
	["Harley Davidson","Ciclomotor","Marca","Moto","Bicicleta","2 Ruedas"],
	["Bebe","Mamadera","Chupete","Nacer","Pañales","Cuna"],
	["Torpedo","Barco","Misil","Explosión","Submarino","Bomba"],
	["Pulmón","Corazón","Respirar","Dos","Tórax","Cuerpo"],
	["Millonario","Jet-Set","Tener","Rico","Dinero","Plata"],
	["Cheque","Banco","Plata","Pagar","Papel","Firmar"],
	["Barril","Cerveza","Tonel","Madera","Vino","Cuba"],
	["Golf","Caddy","Hoyos","Dieciocho","Golpe","Palos"],
	["Huracán","Viento","Ciclón","Tormenta","Tornado","Torbellino"],
	["Mercado De Valores","Bolsa","Acciones","Vender","Wall Street","Comprar"],
	["Escenario","Obra","Actores","Espectáculo","Telón","Teatro"],
	["Vagón De Cola","Final","Vagón","Locomotora","Tren","Ultimo"],
	["Poste","Cerco","Palo","Columna","Mástil","Arco"],
	["Mosquito","Picadura","Rascarse","Raid","Espiral","Insecto"],
	["Pasaporte","Documento","Extranjero","Viajar","Aduana","Visa"],
	["Kremlin","Moscú","URSS","Palacio","Rusia","Plaza Roja"],
	["Manejar","Auto","Volante","Coche","Conductor","Vehículo"],
	["Izquierda","Lado","Derecha","Zurdo","Comunista","Dirección"],
	["Oficial","De","Policía","Esposas","Agente","Patrullero"],
	["Cuadro","Museo","Pintor","Óleo","Caballete","Tela"],
	["Lentillas","Duras","Vista","Gafas","Miopía","Ojos"],
	["Caballo","Estribos","Ensillar","Jinete","Montar","Carrera"],
	["Banco","Cheque","Cuenta","Cajero","Dinero","Cambio"],
	["Huella","Digital","Rastro","Pisada","Señal","Mano"],
	["Monstruo","Miedo","Criatura","Asustar","Horrible","Feo"],
	["Flecha","Arco","Punta","Lanzar","Ballesta","Indios"],
	["Hormiga","Insecto","Comer","Jardín","Fila","Plantas"],
	["Dólar","Verde","Dinero","Moneda","EEUU","Efectivo"],
	["Bruja","Escoba","Fea","Cuentos","Mala","Magia"],
	["Indio","Plumas","Tribu","Carpa","Flecha","Pintura"],
	["Colmillo","Mordedura","Diente","Marfil","Vampiro","Elefante"],
	["Mago","Sombrero","Paloma","Truco","Desaparecer","Varita"],
	["Puerta","Entrada","Cerradura","Llave","Timbre","Casa"],
	["Ancla","Hierro","Clavar","Puntas","Agua","Barco"],
	["Agujero","Pozo","Hueco","Orificio","Hoyo","Colador"],
	["Polo","Pelota","Juego","Deporte","Caballo","Jinete"],
	["Edificio","Departamento","Pisos","Ascensor","Casa","Portero"],
	["Astronauta","Luna","Nasa","Cohete","Espacio","Satélite"],
	["Alien","Sigourney Weaver","Criatura","Octavo","Pasajero","Película"],
	["Ruta","Camino","Autos","Peaje","Autopista","Carretera"],
	["Asfalto","Negro","Pavimento","Carretera","Brea","Alquitrán"],
	["Lasaña","Pasta","Capas","Comida","Italiano","Horno"],
	["Garganta","Cuello","Faringe","Tragar","Amígdalas","Laringe"],
	["Semilla","Plantar","Tierra","Flor","Crecer","Regar"],
	["Marinero","Soldado","Blanco","Puerto","Barco","Popeye"],
	["Sonámbulo","Dormir","Caminar","Sueño","Levantarse","Noche"],
	["Sobre","Carta","Remitente","Correo","Buzón","Sello"],
	["Arco Iris","Lluvia","Cielo","Colores","Curva","Sol"],
	["Peluca","Postizos","Cabeza","Cabellera","Pelado","Artificial"],
	["Pingüino","Antártida","Animal","Blanco","Negro","Pájaro"],
	["Adolescente","Adulto","Chico","Joven","Muchacho","Pubertad"],
	["Aceituna","Negra","Carozo","Olivo","Clemente","Verde"],
	["Adidas","Tres Tiras","Indumentaria","Deportes","Zapatillas","Ropa"],
	["Posar","Cuadro","Pintor","Desnudo","Modelo","Postura"],
	["Belleza","Concurso","Hermosa","Linda","Mujer","Salón"],
	["Libro","Leer","Biblioteca","Hojas","Encuadernado","Pagina"],
	["Águila","Ave","Pájaro","Rapiña","Volar","Alas"],
	["Esponja","Bañarse","Jabón","Frotar","Espuma","Ducha"],
	["Canguro","Animal","Australia","Bolsa","Salto","Mamífero"],
	["Teja","Casa","Rojo","Lluvia","Techo","Cubrir"],
	["Soñar","Noche","Dormir","Despierto","Cama","Pesadilla"],
	["Búho","Árbol","Grito","Pájaro","Sabio","Noche"],
	["Batman","Catwoman","Gotham","Joker","Robin","Superhéroe"],
	["Carpeta","Cuaderno","Hojas","Tapas","Forro","Colegio"],
	["Sauna","Gimnasio","Calor","Transpirar","Vapor","Adelgazar"],
	["Delfín","Ballena","Mar","Animal","Amaestrado","Mamífero"],
	["Popeye","Olivia","Brutus","Dibujo Animado","Marinero","Espinacas"],
	["Vergüenza","Colorado","Papelón","Bochorno","Tímido","Rubor"],
	["Sombra","Luz","Árbol","Noche","Obscuridad","Sol"],
	["Lápiz","Escribir","Mina","Goma","Sacar Punta","Borrar"],
	["Mojado","Paraguas","Lluvia","Agua","Seco","Toalla"],
	["Cuna","Dormir","Bebé","Canción","Barrotes","Muebles"],
	["Radiador","Anticongelante","Enfriar","Coche","Agua","Motor"],
	["Reloj","Hora","Tiempo","Despertador","Muñeca","Agujas"],
	["Cowboy","Pistola","Sombrero","Caballo","Indios","Oeste"],
	["Camello","Animal","Desierto","Joroba","Arena","Dromedario"],
	["Herida","Sangre","Corte","Tirita","Coser","Puntos"],
	["Circo","Pista","Carpa","Payasos","Trapecista","Domador"],
	["Bebida","Liquido","Tomar","Agua","Sed","Brindar"],
	["Boleadoras","Cazar","Caballo","Lanzar","Indios","Avestruz"],
	["Pan","Harina","Levadura","Galletitas","Sándwich","Tostadas"],
	["Gasolina","Combustible","Surtidor","Coche","Depósito","Repostar"],
	["Tesoro","Piratas","Mapa","Cofre","Oro","Isla"],
	["Corbata","Vestir","Seda","Camisa","Cuello","Nudo"],
	["Playa","Arena","Costa","Verano","Mar","Mar"],
	["Ladrillo","Construir","Casa","Barro","Edificio","Obra"],
	["Tranvía","Trolebús","Eléctrico","Calle","Vías","Tren"],
	["Trigo","Harina","Grano","Pan","Cereal","Espiga"],
	["Ateo","Dios","Creer","Religión","Vida","Muerte"],
	["Puente","Cruzar","Río","Levadizo","Colgante","Sobre"],
	["Dados","Generala","Tirar","Juego","Cubo","Caras"],
	["Escamas","Reptiles","Placas","Piel","Cubrir","Peces"],
	["Remolacha","Comida","Tubérculo","Cocinar","Morada","Azúcar"],
	["Inmortal","Vivir","Morir","Eternidad","Siempre","Perpetuo"],
	["Campana","Tocar","Iglesia","Bronce","Badajo","Escuela"],
	["Mudo","Hablar","Voz","Señas","Sordo","Boca"],
	["Manillar","Bicicleta","Volante","Dirigir","Freno","Timbre"],
	["Iglú","Alaska","Esquimal","Nieve","Casa","Hielo"],
	["Boomerang","Aire","Australia","Forma","Volver","Tirar"],
	["Cortina","Ventana","Tela","Riel","Correr","Cerrar"],
	["Huérfano","Padres","Papa","Mama","Asilo","Adoptar"],
	["Ciego","Bastón","Lazarillo","Ver","Perro","Braille"],
	["Juguete","Chicos","Reyes","Regalo","Chiche","Niños"],
	["Albert Einstein","Relatividad","Teoría","Bomba Atómica","Científico","Físico"],
	["Almohadón","Sofá","Sillón","Apoyacabezas","Plumas","Funda"],
	["Invernadero","Caliente","Cultivar","Cubierto","Plantas","Efecto"],
	["Pistola","Arma","Revolver","Disparar","Balas","Gatillo"],
	["Bombón","Comer","Dulce","Caramelo","Chocolate","Caja"],
	["Descongelar","Derretir","Deshielo","Nevera","Agua","Congelador"],
	["Mafalda","Dibujo","Quino","Chiste","Niña","Manolito"],
	["Receta","Comida","Indicaciones","Ingredientes","Instrucciones","Cocinar"],
	["Ovni","Espacio","Nave","Extraterrestre","Luna","Marciano"],
	["Cementerio","Tumba","Enterrar","Funeral","Muerte","Lápida"],
	["Tarjeta De Crédito","Dinero","Plástico","Comprar","Efectivo","Pagar"],
	["Loco","Desequilibrado","Furioso","Demente","Trastornado","Manicomio"],
	["Abogado","Defensa","Acusado","Letrado","Prueba","Juicio"],
	["Crucero","Barco","Mar","Vacaciones","Viaje","Camarote"],
	["Desayuno","Cena","Almuerzo","Merienda","Levantarse","Mañana"],
	["Ping Pong","Paleta","Red","Pelota","Juego","Tenis De Mesa"],
	["Comisaría","Patrullero","Policía","Detenerse","Barrio","Calabozo"],
	["Canoa","Agua","Navegar","Indio","Remo","Bote"],
	["Biblioteca","Escritores","Leer","Libros","Silencio","Fichero"],
	["Avión","Alas","Aire","Volar","Piloto","Aeropuerto"],
	["Guante","Manos","Dedos","Invierno","Boxeador","Lana"],
	["Entrada","Puerta","Dentro","Acceso","Ingreso","Salida"],
	["Preciosa","Bella","Hermosa","Linda","Bonita","Piedra"],
	["Turista","Extranjero","Viaje","Visitar","Hotel","Vacaciones"],
	["Pornografía","Erotismo","Censura","Revistas","Películas","Obsceno"],
	["Calzoncillos","Bombacha","Hombre","Slip","Pantalón","Ropa Interior"],
	["Frígida","Insensible","Mujer","Placer","Orgasmo","Sexual"],
	["Uniforme","Vestido","Igual","Colegio","Ejercito","Policía"],
	["Fontanero","Gotera","Agua","Caños","Arreglar","Tuberías"],
	["Dedal","Aguja","Pinchar","Metal","Protección","Coser"],
	["Farmacia","Medico","Inyección","Remedios","Receta","Turno"],
	["Algodón","Cura","Sangre","Herida","Rama","Farmacia"],
	["Brújula","Orientarse","Norte","Aguja","Imán","Cardinales"],
	["Azulejo","Cerámica","Pared","Baño","Cocina","Decoración"],
	["Andén","Tren","Estación","Esperar","Subir","Bajar"],
	["Cicatriz","Señal","Marca","Herida","Piel","Huella"],
	["Corona","Rey","Cabeza","Oro","Redonda","Símbolo"],
	["Anestesia","Dolor","Operación","Dormir","Sentir","Médico"],
	["Bala","Cartucho","Pistola","Disparar","Proyectil","Escopeta"],
	["Sombrero","Gorra","Casco","Poner","Cabeza","Ala"],
	["Antepasado","Árbol Genealógico","Descendiente","Familiar","Abuelo","Ascendiente"],
	["Cliente","Vendedor","Pagar","Comprar","Razón","Negocio"],
	["Ayer","Mañana","Tiempo","Antes","Día","Pasado"],
	["Cuarteto","Instrumentos","Música","Cantantes","Conjunto","Grupo"],
	["Dedo","Mano","Uñas","Nudillos","Anillo","Puño"],
	["Horóscopo","Astrología","Doce","Zodíaco","Signos","Futuro"],
	["Pariente","Abuelos","Padres","Tíos","Familiar","Cónyuge"],
	["Tatuaje","Aguja","Cuerpo","Dibujo","Piel","Tinta"],
	["Toldo","Sol","Lluvia","Balcón","Tela","Protección"],
	["Fumar","Tabaco","Habano","Humo","Pipa","Cigarrillo"],
	["Locutor","Hablar","Radio","TV","Noticias","Avisos"],
	["Ataúd","Cajón","Muerto","Enterrar","Cementerio","Velorio"],
	["Ajedrez","Juego","Tablero","Ficha","Blancas","Negras"],
	["Cita","Reunión","Fecha","Pedir","Encontrarse","Teléfono"],
	["Trenza","Niña","Peinado","Cabeza","Pelo","Tres"],
	["Ombligo","Tripa","Cordón","Cicatriz","Marca","Umbilical"],
	["Ventrílocuo","Muñeco","José Luis Moreno","Hablar","Vientre","Boca"],
	["Lámpara De Noche","Luz","Bombilla","Leer","Cama","Mesa"],
	["Bandera","Flamear","País","Mástil","Azul","Símbolo"],
	["Sherlock Holmes","Watson","Detective","Lupa","Pipa","Inglés"],
	["Elegante","Atractivo","Aspecto","Encantador","Bien Vestido","Ropa"],
	["Billar","Juego","Bolas","Pool","Taco","Carambola"],
	["Prostituta","Puta","Mujer","Pagar","Profesional","Calle"],
	["Esteroides","Doping","Droga","Atleta","Hormonas","Músculos"],
	["Simple","Difícil","Doble","Fácil","Compuesto","Sencillo"],
	["Cebra","Animal","Blanco","Caballo","Rayado","Negro"],
	["Soltero","Casado","Novio","Estado Civil","Compromiso","Despedida"],
	["Peluquero","Afeitar","Cabello","Cortar","Tijeras","Bigotes"],
	["Telescopio","Astrónomo","Estrellas","Observatorio","Planetas","Microscopio"],
	["Caballos","Apuestas","Hipódromo","Pura Sangre","Carreras","Jockey"],
	["Diccionario","Definición","Libro","Palabra","Significado","Larousse"],
	["Colectivero","Boleto","Conductor","Manejar","Transporte","Volante"],
	["Planeador","Volar","Avión","Motor","Alas","Piloto"],
	["Broma","Chiste","Cómico","Chanza","Risa","Diversión"],
	["Aplauso","Golpear","Palmas","Manos","Ovación","Espectáculo"],
	["Orquesta","Director","Instrumentos","Músicos","Concierto","Sinfonía"],
	["Altavoz","Bafle","Escuchar","Música","Estéreo","Bluetooth"],
	["Apostador","Perder","Ganar","Lotería","Jugar","Carreras"],
	["Máscara","Carnaval","Antifaz","Cara","Disfraz","Cubrir"],
	["División","Aritmética","Colegio","Matemática","Calculadora","Multiplicación"],
	["Congelador","Conservar","Comida","Frío","Nevera","Hielo"],
	["Trident","Chicle","Globo","Quiosco","Masticas","Marca"],
	["Dinamarca","Sirenita","Europa","Escandinavo","País","Copenhague"],
	["Hipódromo","Carreras","Caballos","Apuestas","Moncloa","Dinero"],
	["Hilo","Zurcir","Aguja","Enhebrar","Cosas","Botón"],
	["Sudor","Transpirar","Piel","Ejercicio","Calor","Desodorante"],
	["Roncar","Noche","Ruido","Nariz","Dormir","Molestar"],
	["Pinocho","Mentira","Nariz","Gepetto","Muñeco","Cuento"],
	["Confucio","Filósofo","Chino","Proverbio","Religión","Sabio"],
	["Cerdo","Animal","Embutido","Jamón","Chancho","Fiambre"],
	["Compact Disc","Escuchar","Láser","Canción","Casette","Música"],
	["Arroz","Cereal","Comida","Grano","Chino","Integral"],
	["Pintar","Artista","Cuadro","Colores","Pincel","Pared"],
	["Ciudad","Municipio","Capital","Población","Edificios","Alcalde"],
	["Parquímetro","Ficha","Coche","Estacionar","Tiempo","Reloj"],
	["Fiesta","Cumpleaños","Celebración","Regalos","Amigos","Invitaciones"],
	["Olímpico","Atletas","Medallas","Juegos","Competición","Países"],
	["Asado","Fuego","Parrilla","Carbón","Carne","Cocinar"],
	["Insomnio","Cama","Dormir","Desvelo","Sueño","Noche"],
	["Gatillo","Dedo","Tirar","Apretar","Disparar","Pistola"],
	["Percha","Colgar","Ropa","Armario","Arruga","Vestido"],
	["Antena","TV","Radio","Captar","Emisión","Onda"],
	["Singular","Plural","Individual","Uno","Particular","Solo"],
	["Ballena","Mar","Animal","Grande","Surtidor","Moby Dick"],
	["Clínex","Nariz","Papel","Desechable","Pañuelo","Mocos"],
	["Chocolate","Comer","Bombón","Dulce","Cacao","Alfajor"],
	["Iberia","British","Barajas","Aviones","Volar","Compañía"],
	["Vóley","Pelota","Juego","Remate","Saque","Red"],
	["Tortuga","Animal","Ninja","Lenta","Caparazón","Leonardo"],
	["Plaza","Chicos","Árboles","Jugar","Tobogán","Hamacas"],
	["Precipicio","Altura","Caer","Montaña","Barranco","Abismo"],
	["Explosión","Pólvora","Detonador","Bomba","Ruido","Dinamita"],
	["Reina","Corona","Monarquía","Príncipe","Inglaterra","Mujer"],
	["Mejilla","Beso","Cara","Bofetada","Cachete","Moflete"],
	["Soldado","Conscripto","Guerra","Militar","Colimba","Ejercito"],
	["Postal","Correo","Vacaciones","Recuerdos","Foto","Cartero"],
	["Misil","Cohete","Nuclear","Proyectil","Arma","Explosión"],
	["Conejo","Animal","Dientes","Orejas","Bugs Bunny","Zanahoria"],
	["Linterna","Luz","Portátil","Lámpara","Pilas","Farol"],
	["Positivo","Resultado","Si","Mas","Negativo","Signo"],
	["Caramelo","Papel","Sugus","Caries","Dulce","Quiosco"],
	["Amenaza","Asustar","Carta","Peligro","Advertencia","Aviso"],
	["Carnicero","Vender","Vaca","Comprar","Asado","Mercado"],
	["Ampolla","Herida","Piel","Quemadura","Roce","Zapatos"],
	["Ayuda","Apoyo","Auxilio","Socorro","Problema","Asistencia"],
	["Cosecha","Siembra","Recolección","Fruta","Trigo","Campesino"],
	["Termo","Botella","Caliente","Frío","Agua","Mate"],
	["Rating","Encuesta","Opinión","TV","Programa","Porcentaje"],
	["Cactus","Pincha","Agua","Arena","Desierto","Planta"],
	["Apartamento","Ascensor","Alquilar","Edificio","Piso","Vivienda"],
	["Barrio","Calle","Casa","Vecindario","Gente","Ciudad"],
	["Claustrofobia","Cerrado","Miedo","Pánico","Sensación","Angustia"],
	["Club","Deportes","Socio","Cuota","Jugar","Vestuario"],
	["Microondas","Cocinar","Horno","Descongelar","Comida","Eléctrico"],
	["Australia","Canguro","Isla","Koala","País","Sídney"],
	["Mostaza","Hellman’s","Condimento","Perrito Caliente","Hamburguesa","Salchicha"],
	["Revista","Diario","Fotos","Leer","Publicación","Quiosco"],
	["Señal","Marca","Huella","Ruta","Cartel","Indicio"],
	["Estufa","Frío","Calentar","Hogar","Invierno","Gas"],
	["Dibujos Animados","Disney","Caricatura","Niños","Película","Tom & Jerry"],
	["Desodorante","Transpiración","Olor","Aerosol","Perfume","Axilas"],
	["Béisbol","Golpe","Base","Juego","Bate","Deporte"],
	["Enfermera","Doctor","Consultorio","Medico","Hospital","Blanco"],
	["Termómetro","Medir","Fiebre","Axila","Temperatura","Cuerpo"],
	["Costa","Agua","Playa","Orilla","Mar","Río"],
	["Paquete","Correo","Envolver","Caja","Atar","Regalo"],
	["Bus Escolar","Colegio","Niño","Vehículo","Chicos","Amarillo"],
	["Grúa","Levantar","Auto","Avería","Estacionamiento","Auxilio"],
	["Incendio","Quemar","Apagar","Fuego","Llama","Bomberos"],
	["Poncho","Gaucho","Cubrir","Ropa","Cabeza","Capa"],
	["Pochoclo","Maíz","Dulce","Salado","Cine","Blanco"],
	["Humor","Alegría","Animo","Broma","Risa","Comedia"],
	["Hámster","Animal","Jaula","Mascota","Rata","Roedor"],
	["Pelota","Balón","Redonda","Fútbol","Bola","Baloncesto"],
	["Edad","Años","Vida","Nacer","Fecha","Tiempo"],
	["Firma","Nombre","Apellido","Rubrica","Autógrafo","Contrato"],
	["Medialuna","Panadería","Factura","Comer","Grasa","Croissant"],
	["Aguijón","Clavar","Abeja","Veneno","Mosquito","Avispa"],
	["Lanzar","Pelota","Jabalina","Tirar","Echar","Arrojar"],
	["Escarbadientes","Madera","Palito","Aperitivo","Boca","Hilo Dental"],
	["Intendente","Funcionario","Ciudad","Municipalidad","Grosso","Cargo"],
	["Tieso","Inmóvil","Cadáver","Rígido","Tabla","Duro"],
	["Estornudo","Tos","Resfrió","Nariz","Pañuelo","Pimienta"],
	["Cabaret","Desnudarse","Striptease","Bar","Música","Baile"],
	["Telegrama","Mensaje","Correo","Carta","Urgente","Morse"],
	["Piraña","Morder","Comer","Pez","Diente","Río"],
	["Fantasía","Imaginación","Pensamiento","Ilusión","Deseo","Sueño"],
	["Secretaria","Ayudante","Ejecutivo","Oficina","Jefe","Agenda"],
	["Crudo","Cocinar","Fuego","Cocido","Comida","Carne"],
	["Dinamita","Nobel","Mecha","Bomba","Tnt","Explosión"],
	["Caníbal","Comer","Salvaje","Humano","Antropófago","Tribu"],
	["Búfalo","Animal","Buey","Bisonte","Indios","Oeste"],
	["Paracaídas","Tirarse","Altura","Piloto","Saltar","Avión"],
	["Boleto","Tren","Colectivo","Pasaje","Sacar","Micro"],
	["Apellido","Nombre","Familia","Hijo","Padre","Llamarse"],
	["Chicle","Trident","Golosina","Boomer","Globo","Masticar"],
	["Eco","Voz","Sonido","Repetir","Montaña","Gritar"],
	["Código","Lenguaje","Morse","Descifrar","Secreto","Clave"],
	["Acuario","Agua","Mar","Zoológico","Pecera","Casa"],
	["Trofeo","Carrera","Ganar","Campeón","Premio","Copa"],
	["Bikini","Tanga","Playa","Baño","Malla","Dos Partes"],
	["Violín","Cuerdas","Instrumento","Música","Arco","Stradivarius"],
	["Retrato","Identikit","Cara","Dibujar","Fotografía","Pintura"],
	["Falso","Mentir","Verdadero","Incorrecto","Dinero","Timador"],
	["Sirena","Pez","Canto","Mar","Cola","Mujer"],
	["Secreto","Confidencial","Saber","Conservar","Decir","Guardar"],
	["Muletas","Caminar","Discapacitado","Yeso","Pierna","Roto"],
	["Tabaco","Cigarrillo","Hojas","Fumar","Habano","Pipa"],
	["Parasol","Luz","Playa","Paraguas","Proteger","Sombrilla"],
	["Biblia","Religión","Dios","Libro","Santo","Testamento"],
	["Pluma","Escribir","Almohada","Ave","Pájaro","Alas"],
	["Ataque","Asalto","Violencia","Agresión","Defender","Ofensiva"],
	["Bombacha","Ropa","Corpiño","Tanga","Calzoncillo","Mujer"],
	["Visa","Tarjeta","Master Card","Débito","Crédito","Pagar"],
	["Bisturí","Quirófano","Instrumento","Cortar","Cirujano","Operar"],
	["Virgen","Maria","Hombre","Himen","Fátima","Sexo"],
	["El País","Diario","Periódico","Titulares","Periodistas","Noticias"],
	["Johnson’s","Champú","Pelo","Lavar","Jabón","Marca"],
	["Parte","Entero","Trozo","Pedazo","Fracción","Fragmento"],
	["Debut","Primera Vez","Artista","Estreno","Virgen","Comienzo"],
	["Enredadera","Jardín","Subir","Planta","Pared","Trepar"],
	["Venecia","Italia","Ciudad","Agua","Canales","Góndolas"],
	["Pala","Herramienta","Sacar","Pozo","Tierra","Agujero"],
	["Novia","Soltera","Blanco","Casarse","Vestido","Ramo"],
	["Himen","Virgen","Mujer","Vagina","Membrana","Sexo"],
	["Pájaro","Nido","Volar","Piar","Alas","Aves"],
	["Escorpión","Aguijón","Desierto","Alacrán","Picar","Veneno"],
	["Lagrima","Ojos","Llorar","Agua","Gotas","Triste"],
	["Hipnotizar","Dormir","Mirada","Mago","Despertar","Sueño"],
	["Fecha","Mes","Año","Almanaque","Día","Calendario"],
	["Carrefour","Supermercado","Caja","Carrito","Comprar","Góndolas"],
	["Levadura","Masa","Pan","Harina","Cocinar","Royal"],
	["Noche","Día","Oscuridad","Luna","Estrellas","Sol"],
	["Dinero","Comprar","Plata","Moneda","Billetes","Guita"],
	["Surf","Playa","Tabla","Mar","Olas","Equilibrio"],
	["Sugus","Caramelo","Masticar","Quiosco","Marca","Golosina"],
	["Inodoro","Caca","Pis","Baño","Agua","Sentarse"],
	["Submarino","Barco","Periscopio","Torpedo","Inmersión","Guerra"],
	["Ventana","Casa","Pared","Vidrio","Mirar","Luz"],
	["Maratón","Carrera","Competición","Kilómetros","Olimpiadas","Grecia"],
	["Whisky","Licor","Alcohol","Tomar","Caro","Bebida"],
	["Taxi","Reloj","Ficha","Coche","Alquiler","Amarillo"],
	["Depresión","Bajón","Animo","Contento","Tristeza","Mal"],
	["Fama","Reputación","Artistas","Celebridad","Popular","Conocido"],
	["Profesor","Enseñar","Universidad","Colegio","Facultad","Secundaria"],
	["Abanico","España","Aire","Mujer","Plegable","Calor"],
	["Aguja","Pajar","Coser","Alfiler","Costura","Hilo"],
	["Cenicero","Cigarrillo","Colilla","Fumar","Fósforo","Habano"],
	["Terraza","Arriba","Plantas","Sol","Techo","Ropa"],
	["Llamar","Nombre","Citar","Che","Venir","Teléfono"],
	["Golondrinas","Pájaro","Primavera","Negro","Volar","Volver"],
	["Ratonera","Trampa","Queso","Cebo","Roedor","Atrapar"],
	["Manicura","Dedos","Cuidar","Uñas","Peluquería","Mujer"],
	["Pared","Casa","Separar","Muro","Tabique","Ladrillos"],
	["Azúcar","Blanco","Endulzar","Edulcorante","Café","Caramelo"],
	["Piano","Instrumento","Música","Teclado","Tocar","Manos"],
	["Cirugía Estética","Operación","Botox","Lifting","Arruga","Silicona"],
	["Embajador","País","Diplomático","Extranjero","Político","Representar"],
	["Dentista","Boca","Caries","Torno","Anestesia","Muelas"],
	["Pirelli","Neumáticos","Ruedas","Llanta","Coche","Michelín"],
	["Poema","Palabra","Escribir","Rima","Verso","Canción"],
	["Zapatillas","Calzado","Caminar","Deportes","Suela","Medias"],
	["Revolución","De Mayo","Levantamiento","Francesa","Movimiento","Sublevación"],
	["Viuda","Marido","Negro","Muerte","Mujer","Duelo"],
	["Cara","Frente","Boca","Ojos","Cabeza","Nariz"],
	["Vacaciones","Trabajo","Descanso","Verano","Playa","Puente"],
	["Títere","Marioneta","Hilos","Madera","Muñecos","Mano"],
	["Picnic","Cesta","Comer","Pasto","Excursión","Domingo"],
	["Pádel","Paleta","Tenis","Red","Deporte","Paredes"],
	["Axe (Desodorante)","Axilas","Perfume","Desodorante","Espray","Aerosol"],
	["Llave","Puerta","Candado","Coche","Cerradura","Abrir"],
	["Diego Maradona","Droga","Numero 10","Boca","Nápoles","Fútbol"],
	["Antiguo","Edad","Tiempo","Años","Historia","Viejo"],
	["Anuncio","Publicidad","Vender","Producto","Tele","Antena 3"],
	["Tierra","Hemisferios","Planta","Mundo","Planeta","Maceta"],
	["Rescate","Dinero","Pago","Rehén","Secuestrar","Instrucciones"],
	["Fidel Castro","Barba","Cuba","Caribe","Presidente","Revolución"],
	["Calvo","Cabeza","Alopecia","Pelo","Cabello","Peluquín"],
	["Cartas De Tarot","Bola De Cristal","Adivinar","Futuro","Gitano","Naipes"],
	["Vagabundo","Mendigo","Linyera","Ciruja","Pobre","Casa"],
	["Escoba","Barrer","Limpiar","Bruja","Piso","Paja"],
	["Toilette","Baño","Recepción","Inodoro","Pintarse","Lavarse"],
	["Miel","Abejas","Dulce","Panal","Colmena","Insecto"],
	["Vino","Alcohol","Bebida","Uvas","Tinto","Blanco"],
	["Lapicero","Sacapuntas","Escribir","Papel","Grafito","Borrar"],
	["Año Nuevo","Enero","Nochevieja","Primero","Navidad","Diciembre"],
	["Escalera","Peldaño","Ascensor","Bajar","Subir","Baranda"],
	["Tenis","Deporte","Pelota","Cancha","Raqueta","Red"],
	["País","Estado","Nación","Gobierno","Frontera","Bandera"],
	["Quiosco","Golosinas","Negocio","Caramelos","Cigarrillos","Vender"],
	["Arena","Playa","Fina","Piedra","Rocas","Erosión"],
	["Aluminio","Metal","Cacerola","Avión","Acero","Liviano"],
	["Costillas","Esqueleto","Caja Torácica","Huesos","Pecho","Cuerpo"],
	["Colchón","Cama","Almohada","Acostarse","Sabanas","Dormir"],
	["Botella","Tapón","Envase","Recipiente","Vidrio","Frasco"],
	["Columna Vertebral","Esqueleto","Cuerpo","Costillas","Huesos","Sostener"],
	["Pijama","Dormir","Cama","Ponerse","Ropa","Camisón"],
	["Color","Amarillo","Tojo","Verde","Azul","Marrón"],
	["Hospital","Doctor","Medico","Curar","Urgencias","Enfermo"],
	["Almíbar","Azúcar","Dulce","Fruta","Lata","Liquido"],
	["Florero","Planta","Recipiente","Ramo","Pote","Agua"],
	["Pirata","Calavera","Abordaje","Barcos","Mar","Pata"],
	["Inyección","Jeringa","Aguja","Pinchar","Cola","Dolor"],
	["Domicilio","Vivir","Casa","Calle","Dirección","Numero"],
	["Rally","Carrera","Coche","Dakar","Sainz","Copiloto"],
	["Jazz","Música","Nueva Orleans","Piano","Negro","Trompeta"],
	["Ametralladora","Arma","Automático","Disparar","Balas","Gatillo"],
	["Trineo","Esquíes","Patinar","Nieve","Perros","Hielo"],
	["Amnesia","Recuerdos","Memoria","Acordarse","Cabeza","Olvidarse"],
	["Ensalada","Comida","Fría","Lechuga","Mixta","Tomate"],
	["Beso","Boca","Mejilla","Amor","Judas","Labios"],
	["Veneno","Antídoto","Víbora","Mortal","Picadura","Cianuro"],
	["Amazona","Mujer","Caballo","Montar","Jinete","Galopar"],
	["Guillotina","Cortar","Cuchilla","Cabeza","Francia","Revolución"],
	["Pulpo","Ocho","Tentáculos","Tinta","Pescadera","Océano"],
	["Divorciado","Casado","Estado Civil","Matrimonio","Separado","Ex"],
	["Oculista","Consulta","Vista","Miope","Lentes","Medico"],
	["Kellogg’s","Cereales","Leche","Tazón","Marca","Desayuno"],
	["Trampolín","Pileta","Zambullida","Nadar","Agua","Tirarse"],
	["Clemente","Seleccionador","Athletic","Vasco","Entrenador","Fútbol"],
	["Carpintero","Madera","Lija","Ebanista","Barnizar","Mueble"],
	["Smoking","Traje De Etiqueta","Boda","Negro","Gala","Frac"],
	["Viagra","Pastilla","Azul","Sexo","Erección","Viejo"],
	["Álbum","Recuerdos","Colección","Fotos","Libro","Boda"],
	["Agua","Liquido","Beber","Tomar","Sed","H2o"],
	["Campana Extractora","Cocina","Vitrocerámica","Sacar","Aire","Humo"],
	["Autógrafo","Fan","Bolígrafo","Famoso","Firma","Nombre"],
	["Calculadora","Operaciones","Maquina","Aparato","Números","Pilas"],
	["Elefante","Marfil","África","Trompa","Colmillo","Dumbo"],
	["Cesto","Ropa","Mimbre","Huevos","Canasta","Guardar"],
	["Yogur","Descremado","Cucharita","Leche","Bebible","Vaca"],
	["Secuestrar","Esconder","Raptar","Rehén","Rescate","Delito"],
	["Ladrón","Robar","Asalto","Bárcenas","Banco","Delincuente"],
	["Tarántula","Negro","Insecto","Araña","Veneno","Peludo"],
	["Amuleto","Talismán","Suerte","Superstición","Pata De Conejo","Herradura"],
	["Novela","Libro","Leer","Escritor","Narración","Cuento"],
	["Plancha","Electrodoméstico","Ropa","Arruga","Apresto","Calor"],
	["Libre","Ocupado","Taxi","Preso","Esclavo","Ave"],
	["Hotel","Alojamiento","Albergue","Pensión","Habitación","Pagar"],
	["Tejer","Agujas","Ovillo","Crochet","Pullover","Lana"],
	["Collar","Perlas","Joya","Colgante","Adorno","Garganta"],
	["Inversión","Finanzas","Bolsa","Dinero","Acciones","Banco"],
	["Colectivo","Boleto","Viajar","Línea","Bondi","Micro"],
	["La Pedriza","Montaña","Madrid","Sierra","Ríos","Senderismo"],
	["Montaña","Esquí","Rocas","Escalar","Everest","Cordillera"],
	["Balcón","Edificio","Departamento","Terraza","Barandilla","Asomar"],
	["Cerveza","Bebida","Mahou","Litrona","Espuma","Rubia"],
	["Comerciante","Negocio","Minorista","Vender","Comprar","Tienda"],
	["Ángel","Paraíso","Diablo","Demonio","Cielo","Alas"],
	["Suerte","Buena","Yeta","Amuleto","Mala","Culo"],
	["Fútbol","Barça","Real Madrid","Portería","Gol","Pelota"],
	["Pollo","Ave","Plumas","Comer","Gallina","Pavo"],
	["Hoja","Verde","Caer","Árbol","Planta","Rama"],
	["Sala De Espera","Consultorio","Revistas","Paciente","Medico","Asientos"],
	["Artista","Pintor","Escultor","Actor","Fama","Premio"],
	["Gorila","Mono","Chimpancé","Orangután","King-Kong","Zoológico"],
	["Alfombra","Carpeta","Persa","Piso","Moqueta","Suelo"],
	["Análisis","Sangre","Orina","Laboratorio","Medico","Enfermo"],
	["Puñal","Arma","Mano","Cuchillo","Espada","Daga"],
	["Colador","Té","Agujeros","Filtro","Fideos","Agua"],
	["Anzuelo","Caña","Pescador","Tirar","Cebo","Lombriz"],
	["Colonia","Desodorante","Aroma","Perfume","Olor","Fragancia"],
	["Índice","Orden","Libro","Principio","Paginas","Final"],
	["Propina","Mozo","Acomodador","Cine","Dinero","Asiento"],
	["Pavo Real","Pájaro","Ave","Pollo","Plumas","Cola"],
	["Ronald Reagan","Bush","Actor","Político","Presidente","EE.UU."],
	["Mensajero","Telegrama","Carta","Paquetes","Moto","Envío"],
	["Espuma","Burbujas","Cerveza","Lavado","Olas","Jabón"],
	["Caspa","Cuero Cabelludo","Cabeza","Champú","Pelo","Tener"],
	["Paciente","Hospital","Esperar","Curarse","Doctor","Enfermo"],
	["Horno","Microondas","Gas","Comida","Calor","Cocina"],
	["Diligencia","Carruaje","Caballo","Transporte","Vaquero","Oeste"],
	["Guitarra","Tocar","Música","Cuerdas","Eléctrica","Instrumento"],
	["Amanecer","Día","Noche","Sol","Alba","Principio"],
	["Epidemia","Vacuna","Enfermedad","Contagiarse","País","Muertos"],
	["Viejo","Joven","Jubilado","Abuelo","Nuevo","Antiguo"],
	["Dálmata","Animal","Perro","Raza","Manchas","Ladrar"],
	["IBM","Computadora","Impresora","Monitor","Marca","Teclado"],
	["Huevo","Clara","Gallina","Frito","Comida","Yema"],
	["Adán","Serpiente","Eva","Hombre","Manzana","Paraíso"],
	["Burger","Comer","Hamburguesa","Hipopótamo","Mc Donald's","Comida Rápida"],
	["Esclavo","Encadenado","Libre","Escapar","Cautivo","Prisionero"],
	["Nudillo","Hueso","Articulación","Parte","Mano","Dedo"],
	["Murciélago","Vampiro","Colmillos","Batman","Sangre","Noche"],
	["Disfraz","Baile","Traje","Carnaval","Mascara","Fiesta"],
	["Carnada","Cebo","Caña","Anzuelo","Pescar","Lombriz"],
	["Amor","Querer","Casamiento","Corazón","Afecto","Odio"],
	["Pelé","Fútbol","Número 10","Brasileño","Disfunción Eréctil","New York Cosmos"],
	["Cangrejo","Pinzas","Crustáceo","Caparazón","Caminar","Mar"],
	["Truco","Flor","Juego","Envido","Quiero","Cartas"],
	["Teatro","Escena","Función","Actores","Director","Telón"],
	["Pomada","Ungüento","Piel","Untar","Crema","Medicamento"],
	["Bingo","Lotería","Azar","Juego","Números","Tarjetas"],
	["Pañal","Bebe","Caca","Pis","Descartable","Talco"],
	["Jersey","Lana","Invierno","Abrigo","Suéter","Tejido"],
	["Jadear","Gemir","Gritar","Respirar","Boca","Gozar"],
	["Rambo","Sylvester Stallone","Rocky","Actor","Película","Vietnam"],
	["Olor","Sentido","Nariz","Aroma","Fragancia","Perfume"],
	["Espalda","Columna Vertebral","Hombros","Pecho","Mochila","Cuerpo"],
	["Desierto","Oasis","Arena","Sol","Sahara","Espejismo"],
	["Tambor","Palillos","Batería","Percusión","Música","Instrumento"],
	["Bambi","Animal","Ciervo","Dibujo Animado","Madre","Walt Disney"],
	["Pollera","Mini","Ropa","Mujer","Falda","Vestido"],
	["Equipaje","Bolsos","Bultos","Perder","Valija","Viaje"],
	["Coincidencia","Inesperado","Casualidad","Azar","Involuntario","Suerte"],
	["Cine","Película","Pantalla","Filmar","Proyectar","Cámara"],
	["Nube","Cielo","Despejado","Lluvia","Sol","Trueno"],
	["Arquitecto","Obra","Planos","Dibujo","Diseño","Construcción"],
	["Calendario","Mes","Almanaque","Fecha","Días","Año"],
	["Muñeco","Niñas","Bebote","Juguete","Mama","Regalo"],
	["Teléfono Público","Llamar","Calle","Hablar","Cabina","Monedas"],
	["Fotografía","Revelar","Rollo","Film","Álbum","Cámara"],
	["Diablo","Lucifer","Ángel","Demonio","Infierno","Satanás"],
	["Batería","Platillos","Instrumento","Música","Pila","Energía"],
	["Almohada","Cama","Dormir","Pluma","Acostarse","Cabeza"],
	["Inocente","Absuelto","Niño","Culpable","Ingenuo","Veredicto"],
	["Voto","Sufragio","Presidente","Emitir","Elecciones","Urna"],
	["Ducha","Baño","Grifo","Bañera","Agua","Cuerpo"],
	["Uva","Vid","Fruta","Parra","Racimo","Vino"],
	["Portero","Mantenimiento","Encargado","Edificio","Basura","Limpio"],
	["Fuera","Exterior","Salida","Ir","Adentro","Echar"],
	["Nariz","Cara","Tabique","Oler","Fosas","Anteojos"],
	["Cocodrilo","Dientes","Río","Piel","Animal","Caimán"],
	["Jarabe","Liquido","Espeso","Cuchara","Frasco","Tos"],
	["Desfile","Modas","Pasar","Militar","Marcha","12 De Octubre"],
	["Alfabeto","Vocales","Consonantes","Leer","Abecedario","Letras"],
	["Restaurante","Mozos","Mesas","Comer","Carta","Servir"],
	["Bomberos","Incendio","Apagar","Fuego","Sirena","Mangueras"],
	["Paloma","Ave","Pájaro","Plumas","Alas","Paz"],
	["Mentira","Falso","Engaño","Verdad","Confianza","Decir"],
	["Boxeador","Guante","Round","K.O.","Ring","Peso"],
	["Tinta","Bolígrafo","Escribir","Pluma","Pintar","Cartucho"],
	["Otoño","Mes","Estación","Hojas","Verano","Invierno"],
	["Bastón","Apoyar","Rengo","Palo","Caminar","Viejo"],
	["Impuestos","IVA","Pagar","IRPF","Beneficio","Ganancias"],
	["Maquillaje","Perfumería","Belleza","Cosmético","Salir","Arreglarse"],
	["Calle","Avenida","Semáforo","Bulevar","Coches","Cruzar"],
	["Antídoto","Medicamento","Cura","Salvar","Remedio","Veneno"],
	["Metro","Tren","Transporte","Ciudad","Debajo","Estación"],
	["Fotocopia","Duplicado","Xerox","Original","Papel","Hojas"],
	["Pentagrama","Líneas","Cinco","Música","Componer","Notas"],
	["Jardín","Botánico","Pasto","Japonés","Flores","Plantas"],
	["Viceroy","Reloj","No Es Lo Que Tengo","Muñeca","Hora","Marca"],
	["Detective","Crimen","Pista","Investigador","Sherlock Holmes","Lupa"],
	["Fabrica","Industria","Operarios","Producir","Obreros","Maquinas"],
	["Compasión","Sensible","Pena","Piedad","Sensación","Desgracia"],
	["Garaje","Estacionamiento","Automóvil","Parking","Cochera","Guardar"],
	["Sed","Bebida","Gaseosa","Seco","Agua","Calmar"],
	["Negativo","Polos","Mas","Signo","No","Positivo"],
	["Mickey","Walt Disney","Dibujos Animados","Pluto","Ratón","Minnie"],
	["Humo","Smog","Fuego","Quemar","Cigarrillo","Chimenea"],
	["Semáforo","Trafico","Calle","Señal","Rojo","Verde"],
	["Quieto","Agitado","Tranquilo","Inmóvil","Moverse","Sentado"],
	["Fósforos","Madera","Fuego","Prender","Elemento","Cerillas"],
	["Aniversario","Casamiento","Celebración","Festejo","Fecha","Cumpleaños"],
	["Chofer","Coche","Conductor","Conducir","Volante","Autobús"],
	["Planta","Verde","Hojas","Regar","Maceta","Vegetal"],
	["Hacha","Cortar","Bosque","Leñador","Madera","Árbol"],
	["Coca-Cola","Bebida","Gaseosa","Marca","Tomar","Pepsi"],
	["Pritt","Adhesivo","Marca","Colegio","Pegamento","Papel"],
	["Buceador","Agua","Mar","Tubos","Escafandra","Buzo"],
	["Granja","Caballo","Estancia","Vaca","Campo","Ganado"],
	["Corpiño","Ropa","Sostén","Pechos","Mujer","Bombacha"],
	["Convento","Iglesia","Habito","Religión","Monja","Cura"],
	["Rosa","Espinas","Flor","Pantera","Color","Rojo"],
	["Albañil","Construcción","Ladrillo","Casa","Obra","Cemento"],
	["Contrato","Papel","Firmar","Acuerdo","Alquiler","Escritorio"],
	["Baloncesto / Basket","Deporte","Pelota","Equipo","Aro","Triple"],
	["China","Oriental","Amarillo","País","Asia","Muralla"],
	["Pañuelo","Nariz","Sonarse","Tela","Mocos","Resfrió"],
	["Pirámide","Tumba","Momia","Egipto","Keops","Faraón"],
	["Dulce","Chocolate","Caramelo","Sabor","Galletitas","Bombón"],
	["Animal","Vivo","Salvaje","Domestico","Veterinario","Irracional"],
	["Camisa De Fuerza","Mangas","Atar","Manicomio","Loco","Demente"],
	["Mástil","Bandera","Palo","Poste","Izar","Velas"],
	["Electricidad","Luz","Corriente","Energía","Enchufe","Lámpara"],
	["Neón","Luces","Negocios","Tubos","Publicidad","Gas"],
	["Globo","Aire","Soplar","Inflar","Cumpleaños","Boca"],
	["Pata","Pierna","Animal","Garra","Palo","Pisar"],
	["Nudo","Corbata","Marinero","Atar","Lazo","Moño"],
	["Dentadura Postiza","Boca","Corega","Abuelos","Artificial","Dientes"],
	["Minuto","Agujas","Reloj","Tiempo","Segundos","Horas"],
	["Naturaleza","Aire","Verde","Animales","Montaña","Árboles"],
	["Grasa","Aceite","Lubricante","Gordo","Freír","Colesterol"],
	["Pararrayos","Tormenta","Relámpago","Eléctrico","Protección","Techo"],
	["Derecha","Izquierda","Mano","Comer","Escribir","Lado"],
	["Escudo","Protección","Defensa","Metal","Redondo","Brazo"],
	["Jaula","Pájaro","Barrotes","Zoológico","Animal","Escaparse"],
	["Aceite","Condimento","Vinagre","Ensalada","Oliva","Freír"],
	["Activista","Político","Militante","Derecho","Estudiante","Protesta"],
	["Calavera","Cráneo","Pirata","Hamlet","Huesos","Cabeza"],
	["Oficina","Negocio","Administración","Trabajo","Secretaria","Escritorio"],
	["Trompeta","Instrumento","Música","Tocar","Louis Amstrong","Jazz"],
	["Colmena","Abeja","Avispa","Aguijón","Miel","Panal"],
	["Error","Equivocarse","Fallar","Mal","Lapsus","Acierto"],
	["Chimenea","Leña","Humo","Fuego","Madera","Quemar"],
	["Estadio","Espectador","Cancha","Deportivo","Fútbol","Olímpico"],
	["Cama","Dormir","Colchón","Almohada","Acostarse","Sueño"],
	["Ariel","Lavadora","Ropa","Maquina","Detergente","Jabón"],
	["Gafas De Sol","Lentes","Ojos","Oscuros","Luz","Rayban"],
	["Paris","Torre Eiffel","Francia","Charles De Gaulle","Ciudad","Capital"],
	["Telaraña","Polvo","Hilo","Insecto","Plumero","Trampa"],
	["Vampiro","Murciélago","Sangre","Chupar","Drácula","Cuello"],
	["Fax","Copia","Mensaje","Enviar","Rápido","Teléfono"],
	["Choque","Accidente","Coche","Colisión","Golpe","Conducir"],
	["Casino","Apostar","Black Jack","Ruleta","Croupier","Tragamonedas"],
	["Fairy","Vajilla","Platos","Espuma","Jabón","Villarriba"],
	["Tímido","Vergüenza","Rubor","Callado","Temeroso","Miedo"],
	["Reunión","Trabajo","Grupo","Gente","Juntarse","Fiesta"],
	["Jabalina","Lanza","Olimpiadas","Atletismo","Tirar","Disciplina"],
	["Borracho","Mamado","Ebrio","Beber","Vino","Alcohólico"],
	["Diente","Boca","Caries","Muela","Torno","Encías"],
	["Enano","Bajo","Alto","Petiso","Circo","Blancanieves"],
	["Cartera","Bolso","Documentos","Billetera","Mujer","Llaves"],
	["Corazón","Rojo","Amor","Músculo","Sangre","Latir"],
	["Vacunar","Obligatorio","Enfermedad","Sabin","Triple","Prevenir"],
	["Stress","Tensión","Trabajo","Nervios","Presión","Ansiedad"],
	["Levantarse","Pararse","Sentarse","Incorporarse","Acostarse","Elevarse"],
	["Titulo","Libro","Nombre","Palabra","Película","Descripción"],
	["Berenjena","Comer","Cultivar","Planta","Púrpura","Vegetal"],
	["Nido","Pájaro","Pichones","Huevos","Casa","Árbol"],
	["Tienda de campaña","Campamento","Tela","Dormir","Refugio","Vientos"],
	["Estomago","Panza","Tripa","Comida","Cuerpo","Digestión"],
	["Podio","Campeón","Ganador","Pedestal","Triunfador","Subir"],
	["Agenda","Abecedario","Días","Direcciones","Teléfonos","Morgan"],
	["Pizza","Italiana","Mozzarella","Queso","Domino's","Domicilio"],
	["Espía","CIA","Guerra Fría","Traidor","Secreto","James Bond"],
	["Cupido","Arco","Flechazo","Amor","Dios","Corazón"],
	["Pronostico","Predicción","Nublado","Lluvia","Temperatura","Tiempo"],
	["Luna","Noche","Sol","Satélite","Espacio","Estrellas"],
	["Mercenario","Soldado","Guerra","Pago","Extranjero","Militar"],
	["Anillo","Dedos","Mano","Sortija","Compromiso","Alianza"],
	["Estampilla","Carta","Sobre","Correo","Lamer","Sello"],
	["Póker","Apostar","Naipes","Juego","Baraja","Cartas"],
	["Brillante","Diamante","Sol","Luz","Radiante","Luminoso"],
	["Reventar","Explotar","Globo","Bomba","Detonar","Dinamita"],
	["Nota","Musical","Canción","Pentagrama","Sonido","Escala"],
	["Guardaespaldas","Matón","Policía","Detective","Proteger","Cuidar"],
	["Espantapájaros","Asustar","Campo","Aves","C","Proteger"],
	["Tarde","Mañana","Mediodía","Horas","Noche","Siesta"],
	["Abuelo","Nieto","Padre","Viejo","Jubilado","Anciano"],
	["Rinoceronte","Cuerno","Animal","África","Mamífero","Salvaje"],
	["Cobarde","Valor","Atreverse","Miedo","Enfrentar","Defenderse"],
	["Balde","Llevar","Plástico","Recipiente","Agua","Manija"],
	["Papa","Patata","Comer","Puré","Tortilla","Fritas"],
	["Hueso","Esqueleto","Romper","Tuétano","Calcio","Perro"],
	["Soga","Atar","Nudo","Ahorcar","Cuerda","Sujetar"],
	["Acoplado","Camión","Remolque","Carga","Transporte","Detrás"],
	["Batalla","Armas","Combate","Conflicto","Lucha","Guerra"],
	["Unicornio","Cuerno","Animal","Patas","Caballo","Azul"],
	["Destornillador","Herramienta","Mano","Tuerca","Clavo","Vuelta"],
	["Cuchara","Tenedor","Mesa","Comer","Sopa","Cuchillo"],
	["Cuerpo Humano","Anatomía","Piernas","Esqueleto","Cadáver","Músculos"],
	["Acomodador","Cine","Linterna","Asiento","Antiguamente","Película"],
	["Estatua de la Libertad","Mujer","Antorcha","Monumento","EE.UU.","Nueva York"],
	["Prismáticos","Distancia","Lejos","Mirar","Catalejo","Anteojos"],
	["Estrangular","Asesinar","Asfixiar","Matar","Cuello","Garganta"],
	["Satélite","Espacio","TV","Orbita","Luna","Artificial"],
	["Boda","Matrimonio","Novia","Iglesia","Civil","Luna De Miel"],
	["Onda","Ola","Movimiento","Mar","Línea","Curva"],
	["Tren","Vías","Humo","Locomotora","Vehículo","Vagón"],
	["Tocadiscos","Bandeja","Revoluciones","Pasacasete","Púa","Música"],
	["Enchufe","Electricidad","Cables","Luz","Corriente","Electrodomésticos"],
	["Moto","Cilindrada","2 Ruedas","Bicicleta","Manillar","Atasco"],
	["Silla","Respaldo","Sentarse","Descansar","Patas","Mueble"],
	["Estrella","Espacio","Planeta","Luna","Fugaz","Noche"],
	["Tragaperras","Bar","Casino","Maquina","Jugar","Azar"],
	["Fideos","Espagueti","Pasta","Tuco","Tallarín","Comida"],
	["Línea","Raya","Escribir","Trazo","Recta","Curva"],
	["Barandilla","Agarrarse","Escalera","Pasamano","Balcón","Caer"],
	["Sonrisa","Dientes","Labios","Cara","Boca","Alegría"],
	["Jockey (Caballos)","Carrera","Fusta","Hipódromo","Montar","Caballo"],
	["Nesquik","Colacao","Polvo","Chocolate","Cacao","Leche"],
	["Amarillo","Banana","Sol","Color","Limón","Oro"],
	["Cristóbal Colon","12 De Octubre","Descubridor","América","Carabelas","Puerto De Palos"],
	["Capataz","Encargado","Fabrica","Obreros","Mandar","Trabajo"],
	["Relámpago","Descarga","Nube","Tormenta","Rayo","Trueno"]
];